version: '3.8'

services:
  db:
    image: mysql:5.7.41
    environment:
      MYSQL_DATABASE: javagame
      MYSQL_ROOT_PASSWORD: Enr1co.1
    volumes:
      - mysql-data:/var/lib/mysql
  
  app:
    build: 
      context: .
      dockerfile: dockerfile
    image: javagame
    depends_on:
      - db

  adminer:
  image: adminer
  ports:
   - "8081:8080"
  depends_on:
   - db

volumes:
  mysql-data:
